---
      - shell:
          cmd: |
            cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
            [kubernetes]
            name=Kubernetes
            baseurl=https://mirrors.aliyun.com/kubernetes/yum/repos/kubernetes-el7-x86_64/
            enabled=1
            gpgcheck=1
            repo_gpgcheck=1
            gpgkey=https://mirrors.aliyun.com/kubernetes/yum/doc/yum-key.gpg https://mirrors.aliyun.com/kubernetes/yum/doc/rpm-package-key.gpg
        tags: repo   

      - name: Install packages
        yum:
          name: '{{ item }}'
          state: present
        with_items:
          - kubelet
          - kubeadm
          - kubectl 
          - docker
          - kubernetes-cni
        tags: install


